### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by erkinalp** [RandomOrg/JSON-RPC-Python#2]

**Comment by RandomOrgDev** [comment]
Thank you for highlighting this issue. The most recent updates to this repository also include support for both Python 2 and >=3.5 (066715c5cebc4862e3facc23ddbd400c8e7650a1 and 414af93dc7793e4c3d5a0d24c2fd75756a2af90b). Should there be any other issues, do feel free to contact us. Thank you!
