### ISSUE TITLE
Python 3 Compatibility, Updated Tests

### ISSUE THREAD

**Issue by nicorellius** [RandomOrg/JSON-RPC-Python#4]
Greetings, I've been using this package in my own applications, but I need it to be Python 3.6 compatible. I updated a fork of this repo for this purpose and did some PEP 8 cleanup. I updated the tests and they were all passing on my system before this pull request... I was hoping you might merge these changes if you like what you see. Thanks!

**Comment by whatnick** [comment]
+1 Voted for a merge

**Comment by RandomOrgDev** [comment]
Hello, 
thank you for your feedback and your efforts in making the library accessible to Python 3 users. 
The changes pushed to this repository (066715c5cebc4862e3facc23ddbd400c8e7650a1 and 414af93dc7793e4c3d5a0d24c2fd75756a2af90b) have added support for the new methods introduced in Release 2 and 3 of the RANDOM.ORG JSON-RPC API, as well as compatibility for Python versions 2.7 and >= 3.5 simultaneously. The official package on [PyPI](https://pypi.org/project/rdoclient/) has also been updated. 
So, unfortunately, it does not suit to merge the changes in the pull request as our newest updates have provided an alternative solution. Thank you again for your interest and should any other issues arise, please do feel free to contact us!

**Comment by nicorellius** [comment]
Awesome, thank you... and my pleasure. I'm glad it's working for Python 3 from its original source. I'm a big fan of RANDOM.ORG!!!
